---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fs-csi-nodeplugin
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: fs-csi-nodeplugin
aggregationRule:
  clusterRoleSelectors:
    - matchLabels:
        rbac.csi-infiblock-plugin/aggregate-to-fs-csi-nodeplugin: "true"
rules: []
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: fs-csi-nodeplugin-rules
  labels:
    rbac.csi-infifs-plugin/aggregate-to-fs-csi-nodeplugin: "true"
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: fs-csi-nodeplugin
subjects:
  - kind: ServiceAccount
    name: fs-csi-nodeplugin
    namespace: default
roleRef:
  kind: ClusterRole
  name: fs-csi-nodeplugin
  apiGroup: rbac.authorization.k8s.io
